version: "3.9"
services:
  inputti:
    build: ./inputti
    ports:
      - "3000:3000"
  outputti:
    build: ./angular-output
    ports:
      - "4200:80"
  apimango:
    build: ./mongoapi
    ports:
      - "8080:8080"
  mongodb:
    image: "mongo:5.0.0-rc1-focal"
  redisapi:
    build: ./redisapi
    ports:
      - "8070:8070"
  redis:
    image: "redis:6.2.4-alpine"
  dotnet:
    build: ./dotnet
    depends_on:
      - redis
      - mongodb
